### ISSUE TITLE
install-assume-role: completerlocation vs completer_location

### ISSUE THREAD

**Issue by vnr-cpa** [arvatoaws-labs/assume-role#7]
Hi all,

in lines 14, 34 and 52 the variable name is completer_location. In line 33 its completerlocation.
After changing completerlocation to completer_location in line 33 I could use the script.
You might want to change this ;-).

Very helpful tool. Best regards

Christopher

**Comment by kabakakao** [comment]
Hi Christopher,
I fixed the typo.

Regards,
Stephan
